### ISSUE TITLE
Errors: {:unknown_key, %{key: "effectiveGasPrice", value: ...}}

### ISSUE THREAD

**Issue by prostack364** [Sphnyx/sphnyx-explorer#7]
Errors:
  {:unknown_key, %{key: "effectiveGasPrice", value: "0x2540be400"}}

    (ethereum_jsonrpc) lib/ethereum_jsonrpc/receipt.ex:236: EthereumJSONRPC.Receipt.ok!/2
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/receipts.ex:138: EthereumJSONRPC.Receipts.fetch/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<0.25812614/1 in Indexer.Block.Fetcher.Receipts.fetch/2>, [[%{block_hash: "0x28e2744a9cf6dbef627a7942b40a28ac8263a4801959630823f1a9813da65067", block_number: 21651629, from_address_hash: "0x571857d01acf090868aa79334d41e48153bf2820", gas: 5486588, gas_price: 10000000000, hash: "0xa0a1082502c2cf408532b64f0e9f1ecdfdfb45f4df42ffeb5f7ffb1eea67f0e5", index: 0, input: "0x608060405260036001556001600d60006101000a81548160ff0219169083151502179055506040518060400160405280600b81526020017f5555555520544f4b454e4e000000000000000000000000000000000000000000815250600e9080519060200190620000719291906200090b565b506040518060400160405280600481526020017f5555555500000000000000000000000000000000000000000000000000000000815250600f9080519060200190620000bf9291906200090b565b5073571857d01acf090868aa79334d41e48153bf2820601060016101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055506001601360156101000a81548160ff0219169083151502179055503480156200013d57600080fd5b5060405162004671380380620046718339818101604052810190620001639190620009d2565b6012601060006101000a81548160ff021916908360ff1602179055506b019d971e4fe8401e74000000600981905550600954600019620001a4919062000ca4565b600019620001b3919062000bf5565b600a81905550600a54600260008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000208190555080601160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550683635c9adc5dea00000600c8190555062000260620006ac60201b60201c565b6000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550600073d99d1c33f9fc3444f8101754abc46c52416550d190508073ffffffffffffffffffffffffffffffffffffffff1663c45a01556040518163ffffffff1660e01b815260040160206040518083038186803b158015620002ff57600080fd5b505afa15801562000314573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906200033a9190620009d2565b73ffffffffffffffffffffffffffffffffffffffff1663c9c65396308373ffffffffffffffffffffffffffffffffffffffff1663ad5c46486040518163ffffffff1660e01b815260040160206040518083038186803b1580156200039d57600080fd5b505afa158015620003b2573d6000803e3d6000fd5b505050506040513d601f19601f82011682018060405250810190620003d89190620009d2565b6040518363ffffffff1660e01b8152600401620003f792919062000a9b565b602060405180830381600087803b1580156200041257600080fd5b505af115801562000427573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906200044d9190620009d2565b601360006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555080601260006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550620005113073d99d1c33f9fc3444f8101754abc46c52416550d16200050560c8600954620006b460201b620019b71790919060201c565b6200073860201b60201c565b6001600660008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060006101000a81548160ff0219169083151502179055506001600660008060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060006101000a81548160ff0219169083151502179055506001600660003073ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060006101000a81548160ff0219169083151502179055508173ffffffffffffffffffffffffffffffffffffffff16600073ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef6009546040516200069c919062000b2e565b60405180910390a3505062000e75565b600033905090565b600080831415620006c9576000905062000732565b60008284620006d9919062000b94565b9050828482620006ea919062000b5c565b146200072d576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401620007249062000aea565b60405180910390fd5b809150505b92915050565b600073ffffffffffffffffffffffffffffffffffffffff168373ffffffffffffffffffffffffffffffffffffffff161415620007ab576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401620007a29062000b0c565b60405180910390fd5b600073ffffffffffffffffffffffffffffffffffffffff168 (truncated)

**Comment by prostack364** [comment]
Resolved in PR #8
